SIQ_settings_loaded({
    "searchBoxName": "s",
    "postTypesForSearch": "post,page,e-landing-page,product,cpt_portfolio,cpt_services,cpt_team",
    "autocompleteNumRecords": 5,
    "customSearchNumRecords": 10,
    "showACImages": true,
    "disableAutocomplete": false,
    "autocompleteWidth": null,
    "customSearchThumbnailsEnabled": true,
    "resultPageUrl": "https://34.251.246.233/search/",
    "queryParameter": "q",
    "autocompleteTextResults": "Results",
    "autocompleteTextPoweredBy": "powered by",
    "autocompleteTextMoreLink": "Show all # results",
    "feedEnabled": false,
    "crossSiteSearch": false,
    "crossSiteSearchOnPage": false,
    "mobileEnabled": true,
    "mobileStylingBarInputBoxPlaceholder": null,
    "mobileStylingSearchHeadTxt": null,
    "mobileStylingSearchResultStatTxt": null,
    "mobileStylingSearchLoadingTxt": null,
    "mobileStylingBarFavicon": null,
    "mobileFloatSearchIconEnable": false,
    "mobileFloatSearchBarEnable": false,
    "mobileItemTitleTextSize": null,
    "mobileSearchIconSelector": null,
    "siqSid": "11167975",
    "showAuthorAndDate": true,
    "showPostLink": true,
    "showCategory": true,
    "showTag": true,
    "searchAlgorithm": "BROAD_MATCH",
    "customSearchBarPlaceholder": "Enter Your Search Term",
    "customSearchResultsInfoText": "Showing ##offset## to ##limit## of ##total## Results",
    "customSearchResultsOrderRelevanceText": "Relevance",
    "customSearchResultsOrderNewestText": "Newest",
    "customSearchResultsOrderOldestText": "Oldest",
    "paginationPrevText": "Prev",
    "paginationNextText": "Next",
    "noRecordsFoundText": "No records found",
    "jsVersion": null,
    "sortBy": "RELEVANCE",
    "featureExcludeFields": true,
    "isProPack": false,
    "thumbnailType": "crop",
    "resizeFromOriginalImg": false,
    "scripts": ["##BASEURL##js/##VERSION##/autocomplete.js", "##BASEURL##js/##VERSION##/search-results.js", "##BASEURL##js/##VERSION##/siq-mobile.js", "##BASEURL##js/##VERSION##/sa.js"],
    "rawScripts": ["!function(s){var o,a,n,r;void 0!==s&&(o=location.href.replace(/^https?:\\/\\/([^\\/]+).*$/i,\"$1\").toLowerCase(),a=location.href,n=function(e,i,n){var r,t,s;i&&((r=new Image).onerror=r.onload=n,t=null!=i.kw?i.kw.replace(/\\\"/g,\"\"):i.kw,s='{\"sid\":\"'+i.sid+'\",\"said\":\"'+i.said.replace(\"www.\",\"\")+'\",\"kw\":\"'+t+'\",\"source_url\":\"'+a+'\",\"engineKey\":\"'+i.engineKey+'\"'+(i.refURL?',\"external_referrer\":\"'+i.refURL+'\"':\"\")+\"}\",r.src=\"//track.searchiq.co/api/tr?event=\"+encodeURIComponent(\"search\")+\"&eventInfo=\"+encodeURIComponent(s))},r=function(){var e=s(\".holdResults\");if(0!==e.length){for(var i=e.attr(\"class\").split(\" \"),n=-1,r=0;r<i.length;r++){var t=i[r].trim();/^siq_searchIndexResult-\\d+$/.test(t)&&(n=t.replace(/^siq_searchIndexResult-(\\d+)$/,\"$1\"))}if(!(n<0))return{kw:s(\".siq_searchIndex-\"+n).val(),sid:SiqConfig.siqSid,said:o,engineKey:siqConfig.engineKey}}},function(){if(s(document).on(\"click\",\".holdResults .searchWrapperLabel, .holdResults ul li .resultsMore\",function(){n(0,r())}),s(document).on(\"click\",\".siq-autocomplete a\",function(){s(this).hasClass(\"siq-recommended-link\")||0!==s(this).parents(\".siq-recommended-link\").length||n(0,r())}),s(document).on(\"submit\",\"form.siq_searchForm\",function(){n(0,r())}),s(document).on(\"keydown\",function(e){switch((e=e||window.event).which||e.keyCode){case 13:(0<s(\".holdResults\").length&&0<s(\".holdResults .siq-autocomplete.highlighted\").length||s(e.target).is(\"#siq_ajax_search\")||s(e.target).parents(\"form\").is(\"#siq_search_results div.siq_search_ajax.siq_search_box form\"))&&n(0,r())}}),s(document).on(\"click touch\",\".siq_aclinewrap\",function(){n(0,{kw:s(this).parents(\"#siq_mobile\").find(\".siq_searchwrap input.siq_searchfield\").val(),sid:SiqConfig.siqSid,said:o,engineKey:siqConfig.engineKey})}),document.referrer&&document.referrer.replace(/^https?:\\/\\/([^\\/]+).*$/i,\"$1\").toLowerCase()!==o){if(SiqConfig.resultPageUrl.replace(/^https?:/,\"\").replace(/\\?.*$/,\"\")!==location.href.replace(/^https?:/,\"\").replace(/\\?.*$/,\"\"))return;function e(e,i){if(!(e.indexOf(\"?\")<0)){var n=e.substr(e.indexOf(\"?\")+1);if(0!==n.length)for(var r=n.split(\"&\"),t=0;t<r.length;t++){var s=r[t];if(s.indexOf(\"=\")<0&&decodeURIComponent(s)===i)return!0;if(i===decodeURIComponent(s.substr(0,s.indexOf(\"=\"))))return decodeURIComponent(s.substr(s.indexOf(\"=\")+1))}}}var i=e(location.href,SiqConfig.queryParameter)||e(location.href,SiqConfig.searchBoxName);eventData={kw:i,sid:SiqConfig.siqSid,said:o,engineKey:siqConfig.engineKey,refURL:document.referrer},n(0,eventData)}}())}(window.siq_S);", "!function(){\n var img=new Image();\n img.src=\"//api.searchiq.co/live?engineKey=\"+window.siqConfig.engineKey;\n}();"],
    "enableAutocompleteFacet": null,
    "enableResultsPageFacet": null,
    "openResultInTab": false,
    "resultPageLayout": "LIST",
    "hideLogo": false,
    "licensed": true,
    "containerGroupId": null,
    "enablePostTypeFilter": false,
    "defaultThumbnailUrl": "",
    "descriptionFields": null,
    "displayContentFromStart": false,
    "autocompleteTemplate": "default",
    "resultPageTemplate": "default",
    "bannerScript": null,
    "mobileBannerScript": null,
    "domain": "34.251.246.233",
    "multiSelectFacetEnabled": false,
    "listTemplateVersion": null,
    "gridTemplateVersion": null,
    "descriptionSegments": null,
    "enablePopularitySorting": false,
    "autocompleteAlignment": null,
    "autocompleteInputSelector": null,
    "autocompleteWidthType": null,
    "autocompleteTemplateCssUrl": null,
    "eventClickUrlPattern": null,
    "searchPageUrlPattern": null,
    "forceToApplyAutocompleteResult": false,
    "autocompleteFollowUrlByClick": false,
    "enableSearchHistory": false,
    "isPartner": false
})